<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXszQi2D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXszQi2D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXszQi2D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXszQi2D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXszQi2D\App_KernelDevDebugContainer([
    'container.build_hash' => 'XszQi2D',
    'container.build_id' => '355b4f21',
    'container.build_time' => 1601026670,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXszQi2D');
