<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'articles' => [[], ['_controller' => 'App\\Controller\\ArticlesController::showAll'], [], [['text', '/']], [], []],
    'articles_categorie' => [['categorie'], ['_controller' => 'App\\Controller\\ArticlesController::showCategorie'], [], [['variable', '/', '[^/]++', 'categorie', true], ['text', '/articles']], [], []],
    'categories' => [[], ['_controller' => 'App\\Controller\\CategoriesController::index'], [], [['text', '/categories']], [], []],
    'commandes' => [[], ['_controller' => 'App\\Controller\\CommandesController::granted'], [], [['text', '/commandes']], [], []],
    'creer_article' => [[], ['_controller' => 'App\\Controller\\CreerArticleController::creerArticle'], [], [['text', '/creer/article']], [], []],
    'panier' => [[], ['_controller' => 'App\\Controller\\PanierController::showpanier'], [], [['text', '/panier']], [], []],
    'modif_panier' => [['id', 'modif'], ['_controller' => 'App\\Controller\\PanierController::modifOne'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'modif', true], ['variable', '/', '\\d+', 'id', true], ['text', '/panier']], [], []],
    'panier_remove_all' => [['id'], ['_controller' => 'App\\Controller\\PanierController::removeAllArticle'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/panier/removeAll']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_authentication' => [[], ['_controller' => 'App\\Controller\\UserAuthenticationController::index'], [], [['text', '/user/authentication']], [], []],
];
